---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: install MySQL Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: update root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    check_implicit_admin: yes
    password: "{{ mysql.root_password }}"
    login_user: root
    login_password: "{{ mysql.root_password }}"
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: create databases
  mysql_db:
    name: "{{ mysql.database }}"
    state: present
    login_user: root
    login_password: "{{ mysql.root_password }}"
  register: db_created

- name: import dump
  mysql_db:
    name: "{{ mysql.database }}"
    state: import
    login_user: root
    login_password: "{{ mysql.root_password }}"
    target: "{{ nginx.doc_root }}/{{ mysql.dump }}"
  when: (mysql.dump and db_created.changed)

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mysql.root_password }}"
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: create users
  mysql_user:
    name: "{{ mysql.user }}"
    password: "{{ mysql.password }}"
    priv: "*.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql.root_password }}"
