---
- hosts: all
  remote_user: vagrant
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - nginx
    - mysql
    - php
    - xdebug
    - composer
    - oitc
